### ISSUE TITLE
[feature request] add a command line option to not fetch routine source

### ISSUE THREAD

**Issue by pyrocks** [schemaspy/schemaspy#1168]
## Expected Behavior

adding a CLI flag, i.e -noRoutineSource will crawl the routines and add them with their params and return types - but will not include the actual routine source currently displayed under "Definition".
why?  because some functions may contain source I don't want people to see - and all I care about is that they know the routines's signature (params and return type). 
## Current Behavior

routine definition is always displayed

## Possible Solution

I know I can nullify the `routine_definition` column in `selectRoutinesSql` to achieve the same result - but it'd be nice to have this as a flag instead of "tempering" with the queries.
upon implementation of this flag - the values from `routine_definition` would be ignored and replaced with a constant `not available` text or something similar. to make it faster - this would "alter" the query before running to not fetch the source to begin with.

**Comment by pyrocks** [comment]
Hi @npetzall is this planned anytime soon?
If not i'll implement the hack on the query instead - this has become a real issue for me now.

**Comment by npetzall** [comment]
I've been sick and had a lot at work so, haven't had much time lately. So sadly there is no on going work regarding this, but it should hopefully be reasonably prioritized to go into 7.0.0

**Comment by pyrocks** [comment]
Thanks for your time 🙏

**Comment by pyrocks** [comment]
@npetzall awesome thanks! Is there a beta version I can test? Any plans to release this officially soon?

**Comment by npetzall** [comment]
There's a link to snapshot jar that is the latest build of master. This will be for 7.0.0-SNAPSHOT it comes with some breaking changes biggest would be the requirement for Java 17.

**Comment by mor-lehr-deel** [comment]
working as expected, thanks 👍 
when is version 7 expected to be released?
any reason _not_ to use the snapshot version until then (we already use Java 17 with version 6 so that's not an issue)

**Comment by npetzall** [comment]
I would have hoped to have it out by now, but hopefully shortly. I just want the UDT in, I'm struggling because it's pretty big/complex and I'm a bit short on time so I never get a proper sit down. But I think I'm closing in.

Regarding the snapshot, I would say there is no reason not to use it. There might be corporate policies saying you need a fixed version. Since with snapshot changes can be introduced that might break a pipeline or similar. But if your hosting your own repo of tools you can just replace the -SNAPSHOT part with the date you downloaded it or the actual build date of the snapshot.

We have a fair amount of tests and coverage so in most cases a broken snapshot will never be published. No guarantee tho.

The difference is the version tagging but also signing. I'm gonna add a new issue and add signing to snapshots.

**Comment by mor-lehr-deel** [comment]
Thanks again for your time.
Just a tiny clarification - when you say shortly you mean the coming days/week or two - or 3 months... It makes a difference for us :)

**Comment by npetzall** [comment]
Ohh, two weeks I hope.

It's the UDT pull request and checking documentation and populating what's new.

We want to be extra clear on the breaking stuff.
