### ISSUE TITLE
Where is it?

### ISSUE THREAD

**Issue by MichaelDBA** [schemaspy/schemaspy#156]
I cannot locate the jar file anywhere here, or even after downloading the zip file.

**Comment by npetzall** [comment]
@MichaelDBA where is what?
If it's schemaspy.
Under releases here on github you can find jar and sources.
On the first page there are links to both latest release and latest build.

**Comment by rafalkasa** [comment]
@MichaelDBA do you need some help or assistance from us ? 
If you don't have any questions please close the issue.

**Comment by MichaelDBA** [comment]
You should probably add that to the documentation link, http://schemaspy.readthedocs.io/en/latest/installation.html

It only shows how to install some prerequisites. Besides, most github clones or zips include everything to run a tool, not schemaspy.  So I will defer closing this until after you review my request.

Thanks.

**Comment by npetzall** [comment]
@rafalkasa
1, let's add link to github in documentation. 
2, let's add build instructions to readme.md.

We only have a binary which is jar which in turn is more or less a zip file. So no zip of jar. We shouldn't bundle jre or graphviz since they are OS specific.

Clone, build and run is the normal procedure. Not clone and run if you ask me.

**Comment by MichaelDBA** [comment]
thumbs up!
