### ISSUE TITLE
href in Parents column of table page gives 404

### ISSUE THREAD

**Issue by pakomp** [schemaspy/schemaspy#164]
Hi,
Running Schemaspy 6.0.0-rc2 against PostgreSQL db with standard public schema.

When going to the page of a table with a foreign key on a column, the parent table shown in the "Parents" column has href set to "../../public/tables/mytable.html", which makes it 404. 

Guessing it should be either "../tables/mytable.html" or just "mytable.html" instead, and ../public might have something todo with if your are using multiples schemas. 

Affects all tabs "Releated columns"/"Constraint"/"Comments".

**Comment by wkasa** [comment]
@pakomp I reproduced this issue, but only when I had FK in the table in the schema that was not included in the schemaspy.properties. Is your situation the same? do you have more than one schema and trying to run only for one of them?
Maybe there is a different way to reproduce this issue. If yes I'd like to know how to do that.

**Comment by pakomp** [comment]
@wkasa No I only have the default public schema.

So on a empty db if I just run:
CREATE TABLE tables (
  id INTEGER,
    CONSTRAINT tables_pkey PRIMARY KEY(id)
)

CREATE TABLE table_names (
  id INTEGER,
  table_id INTEGER NOT NULL,
  table_name VARCHAR(255) NOT NULL,
  CONSTRAINT "FK_table_id" FOREIGN KEY (table_id)
    REFERENCES tables(id)
) 

I still get it when running
java -jar schemaspy-6.0.0-rc2.jar -o test -host <xxx.xxx.xxx.xxx> -db <DatabaseName> -u <login> -p <pass> -t pgsql -dp postgresql-42.1.4.jar

**Comment by pakomp** [comment]
@wkasa That helped, guess I should have read the docs closer. I just added parameters until it didnt complain about missing options.

**Comment by npetzall** [comment]
@wkasa @rafalkasa seems like we need to fix something. I know in the code that it will query the connection metadata for schema, it is then set in the database model. Since -s was missing and there was no nullpointer exception when creating the schema object it used the schema from connection metadata. However since there is an issue, I'm guessing that somewhere in the code it uses a different schema than the one in the database model,
