### ISSUE TITLE
Hive Support

### ISSUE THREAD

**Issue by vidyadharms** [schemaspy/schemaspy#195]
Does is supports Hive database to get the table metadata? 

If not, is it in the upgrade road map to support Hive in future?

If yes, how long the wait period is expected?

**Comment by npetzall** [comment]
Hi,

If the jdbc driver is properly implemented all you need to do is add a new file in the same folder as the schemaspy-6.0.0-rc2.jar file called hive.properties

```
description=Hive
connectionSpec=[connectionstring]
host=db host
port=db port
db=database name
driver=[fqdn to driver]

# Use -dp to override
driverPath=lib/[nameofjar]
```

anything within [] should be replaced.
ConnectionSpec should contain tokens for `<host>`, `<port>` and `<db>`

The documentation for this is currently in a PR.

Now you only need to add `-t hive` to the commandline.

**Comment by npetzall** [comment]
I'm a bit unavailable right now but normally there is no code changes to support a jdbc compliant database only config and overrides for when the metadata supplied by the jdbc-driver is incorrect.

So if you get it working we would love to add the properties file to the project. If you have any issue we will gladly help. I'll be available on gitter in about 4 hrs.

**Comment by npetzall** [comment]
So I started a hive in docker: https://github.com/big-data-europe/docker-hive (version 2.1.1)
I retrieved the jdbc-driver from hive server (since it's included and very important you have matching versions (might be OK with older driver and never server))

Got it running but failed with stacktrace:
```
Caused by: java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveDatabaseMetaData.getSQLKeywords(HiveDatabaseMetaData.java:583)
	at org.schemaspy.model.Database.getSqlKeywords(Database.java:226)
	at org.schemaspy.model.Database.getQuotedIdentifier(Database.java:254)
	at org.schemaspy.service.TableService.initColumns(TableService.java:65)
	... 24 common frames omitted
```
So I would say improper implementation, and guess what it was addressed in HIVE-17765 and commited Oct 25, 2017.

So either your really lucky and running 2.3.2 (21 days old) or you need to backport the fix I would say.

But then again, schemaspy could be a bit more relaxed when fetching SQLKeywords.
This is however the first problem there might be more. I'll implement a more relaxed approach and see where we end up.

@rafalkasa what do you suppose, it's clearly an issue hive-jdbc. But we add Sql92, failing to fetch from DB could just be a warning and not ERROR/FATAL.

**Comment by vidyadharms** [comment]
Thanks for your quick reply.

I am using HDP v2.6 and Hive 2.6.3.0-235. The Hive metastore is in MySql database.

I have tried jdbc drivers but I am unable to primary keys from the Java code. Looking for SchemaSpy to support Hive database to get metadata.

**Comment by npetzall** [comment]
Do get any errors or stacktrace?

I did the relaxed handling of sqlkeywords in my dev env. To get it to run with 2.1.1. I then ended up with a nullpointer due to inconsistent metadata regarding columnames.

**Comment by vidyadharms** [comment]
No. It just written blank output...

**Comment by npetzall** [comment]
Which version are you using of schemaspy?

**Comment by vidyadharms** [comment]
I have not tried it with schemaspy. I have writtten standalone Java application to connect to Hive using kerberos authentication and get Metadata. I have downoaded the schemaspy-6.0.0-rc2.

**Comment by npetzall** [comment]
Hive has no primary/foreign key or autoincrement.

https://issues.apache.org/jira/plugins/servlet/mobile#issue/HIVE-6905

**Comment by npetzall** [comment]
So I think schemaspy would only give you lots of orphan tables. No implied will be found since lack of primary key.

**Comment by vidyadharms** [comment]
The Hive uses MySql as his metastore in backend and I am thinking of directly quering these meatadata tables to retrieve PK and FK information inside schemaspy  source code if that is possible. 

I just need to understand the schemaspy  code inside out to implement. Can I get some documentation of source code? I will create a another wrapper for Hive db and if it works successfully I will commit back it to schemaspy repo with your permission.

**Comment by npetzall** [comment]
I had a look at the Hive Language Manual I actually has Pk, Fk. They are not validated which is sort of okay. I must have misunderstood something in the jira issue. (might be that it's a jira for multiple thing and some are implemented).

As for documentation, it's sadly the source code itself. As for committing just clone, create a branch and later you can create a pull request and we can review it.

But I would advice you to join us in Gitter, there we can help you without making this issue in to a private chat ;)

**Comment by vidyadharms** [comment]
Sure... Can you share the Gitter link?

**Comment by npetzall** [comment]
It's a badge in the readme.md

https://gitter.im/schemaspy/schemaspy

**Comment by vidyadharms** [comment]
Sorry I missed that...but joined on Gitter...Thanks :)

**Comment by rafalkasa** [comment]
I would like to mention that in Pull Request #196 support for Hive database has been added.
@vidyadharms what do you think the support level is enough for you and we can close you issue ?

**Comment by npetzall** [comment]
I'll close this issue, due to lack of response.

We have issue #275 which isn't hive specific but shows that some hive support exists. If more needs to be done new issue should be created.

Also I don't think we will add any hive-specific code (not in the extent of connecting to two different datasource (metastore))
