### ISSUE TITLE
Procedures & triggers documentation

### ISSUE THREAD

**Issue by danielllek** [schemaspy/schemaspy#207]
Does schemaspy document procedures/triggers?

I can't find it in generated reports.

If does not, it would be nice feature :)

**Comment by rafalkasa** [comment]
Hi @danielllek support for routines (procedures and functions) was added by @danwatt in PR #179.

We have to add the database configuration properties selectRoutinesSql and selectRoutineParametersSql for the top used databases like Oracle and PostgreSQL.  These configuration exists for MySql and MariaDB. The routines support for MSSQL was added in #187 and is working from MSSQL 2008+ above. You have to use as database type parameter `-t mssql12`

Triggers are not yet supported but we can consider your issue as a new feature request.

Because this enhancements are the part of the new release they are only available in the Last Build that you can test here: [schemaspy@latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc2.jar)

**Comment by rafalkasa** [comment]
@danielllek after the last changes #209 please use database type `-t mssql08` instead `-t mssql12`

**Comment by danielllek** [comment]
I'm using 6.0.0-rc2: 
For mysql indeed there's routines.html but it's not referenced anywhere in output, and does not look as good as examples in PR #179 :)
![obraz](https://user-images.githubusercontent.com/4323252/34255988-6a72a00a-e653-11e7-9548-5c1e98cc25d4.png)

**Comment by rafalkasa** [comment]
You must use the last build package you have link above in my comment or you can find the link in the readme.md file. 

Please not download rc2 released version but the last build, unfortunately both of them have the same name, but two different URLs.

**Comment by danielllek** [comment]
Ah, OK, works now (I've downloaded from link above but didn't overwrite). 
Thanks!

**Comment by npetzall** [comment]
@danielllek @rafalkasa @danwatt OK to close?

**Comment by danielllek** [comment]
Ok, thx.

**Comment by JacBotin** [comment]
Hello guys!

Could anyone share the compiled schemaspy.jar file with the inclusion of procedures, without my having to perform all the steps.
Sorry, I do not understand java code, I am a database administrator and I fell in love with this tool to share with systems teams.
Congratulations to all of you.

thanks

**Comment by npetzall** [comment]
@JacBotin There is a link for latest in the readme.

**Comment by JacBotin** [comment]
Hi!

Thank you very much. Sucess.

Greetings.

Em 22 de jun de 2018 16:40, "Nils Petzäll" <notifications@github.com>
escreveu:

**Comment by JacBotin** [comment]
@npetzall 
Sorry, I still need one more help. Does anyone have the property file code to generate the oracle procedure documentation (orathin) ?? (selectRoutinesSql and selectRoutineParametersSql for Oracle)??
Appreciate.

**Comment by npetzall** [comment]
@JacBotin create a new issue, it will be more visible than a closed issue.
