### ISSUE TITLE
ETA to next tag/release?

### ISSUE THREAD

**Issue by alpha0010** [schemaspy/schemaspy#384]
My team prefers to only use versioned builds of software (so the per-commit builds are a no).  However, we would like to use some of the features added since last RC.

Is there any estimate when the next tag will be (whether a release candidate or a full release)?

**Comment by npetzall** [comment]
I'm afraid we don't have an ETA.
But you could use a commit version instead of snapshot.

Jitpack.io has great support for that. It's built and supplied thru maven, with the possibility to download the artifact manually. This would keep the build "locked" instead of snapshot that will change with each commit.

As for the ETA, we have a scope for 6.0.0 that is more or less frozen.
https://github.com/schemaspy/schemaspy/projects/1
There are three issue left until we have finished the content of 6.0.0 unless any critical bugs appear.

Just need to mention that one of the issue has become more complex after it was discovered and a fix was supplied.

**Comment by npetzall** [comment]
6.0.0 has been release.
