### ISSUE TITLE
Wrong 'table_rows' result from information_schema when 2+ instances of same database structure

### ISSUE THREAD

**Issue by cadetjj** [schemaspy/schemaspy#385]
The list of tables displays the number of rows (5th column on the grid).
The number of rows is wrong il you have many databases of same structure ( on mariaDB server ).

this is probably due to SQL request :
  selectRowCountSql=select table_rows row_count from information_schema.tables 
  where table_name=:table 

it should probably use the "table_schema" information to filter the right number :
  selectRowCountSql=select table_rows row_count from information_schema.tables 
  where table_schema=:schema and table_name=:table

**Comment by npetzall** [comment]
Your probably right. I think we've done a similar fix for mysql.

**Comment by npetzall** [comment]
#280 was for mysql, guessing this should be done for mariadb databaseType.

**Comment by npetzall** [comment]
I'll check for differences in sql statements between Mariadb and mysql and see if mariadb can extend mysql with some overrides.

**Comment by npetzall** [comment]
Compared with mysql only two differences. First was the one you pointed out, other was a fix for routines.

Tested with mariadb 10.2 and it needs the same fix as in mysql. 
So mariadb databaseType will extend mysql and override only description, connectionSpec, driver and DriverPath. Since the should be compatible this should be the right way to do it.
