### ISSUE TITLE
Backwards Compatibility: Number of things missing

### ISSUE THREAD

**Issue by Lonzak** [schemaspy/schemaspy#39]
Really great that the work is now continuing on schemaspy!

I just generated the database report and saw that several things are missing:

1. There is now a pagination mechanism and there is no way to be view everything on one page like in the 5.X. version. Or did I miss something? Certainly a question of taste however the 'everything on one page' really helped us for some overview matters and it would be nice to still have that option...

2. Additionally the culmulated number of rows and columns are missing (cp. screenshot) Which is quite important to us. The number of colums I can see in the column tab however rows seems to be completely gone. This was originally my request because in the old version I got an overflow in the datatype since MAX_INTEGER range was probably crossed and I got a neg. value...

3. Orphaned Tables (previously Utility Tables): Would it be possible to add an option to exclude the views and only show real tables? (like it is possible in some of the other tabs)

4. Anomalies: I miss the "Columns that are flagged as both 'nullable' and 'must be unique'" option. Was it removed for a specifc reasion?

![schemaspy](https://cloud.githubusercontent.com/assets/1830174/23364514/aa6493dc-fcff-11e6-8a15-c67363b162ec.png)

**Comment by rafalkasa** [comment]
@Lonzak created by you issue according to point 3 - Exlude Views from  Orphaned Tables will be fixed in issue #48

**Comment by Riggs333** [comment]
Regarding point 4 "missing anomaly - column nullable and must be unique":
This anomaly detection was removed from SchemaSpy **before** it was forked to this GitHub project.
But it was removed **after** the latest release of version 5.0.0. So it never went to "production".
So if you use version 5.0.0 you will still see the anomaly in the report.

See this commit on sourceforge:
https://sourceforge.net/p/schemaspy/code/662/
(Actually it was the very last commit dating back to the year 2014 :-) )
> It turns out that the "anomaly" of nullable primary keys that must be unique is actually in the SQL standard and isn't an anomaly at all.

**Comment by rafalkasa** [comment]
Hi @Lonzak 

SchemaSpy project was improved and most of the missing backward things are available, including:

Fix 1. If you want to see everything on one page please use parameter `-nopages`
Fix 2. To the main page I added some useful simple statistic about the database/schema. You can see this simple statistic on [Sample Output]( http://schemaspy.org/sample/index.html) example
Fix 3. Orphan Tables with excluded views was fixed in issue #48
Fix 4. Please read @Riggs333 explanation above and you can go in the initial details here https://sourceforge.net/p/schemaspy/code/662/

Thank you for your contribution to the project and make SchemaSpy better solution !

**Comment by Lonzak** [comment]
Great work - thanks for your improvements!
