### ISSUE TITLE
PostgreSQL 10.4 - missing routines and check constraints, no custom types, no triggers, and some inmprovement, etc, etc

### ISSUE THREAD

**Issue by zam6ak** [schemaspy/schemaspy#395]
I am using schemaspy v 6.0.0 to generate model from dvdrental sample DB on PostgreSQL v10 (on Windows)

The model DB is described in detail here:
http://www.postgresqltutorial.com/postgresql-sample-database/

Command line used to produce output
`java -jar schemaspy-6.0.0.jar -configFile ./dvdrental.properties -schemas public -hq -imageformat svg`

### Issues:
* DB has 8 functions but none show on "Routines"
* Check constraints are not shown under "Constraints"
  * The sample DB does not come with check constraints. I tested this by adding a table with column that has check constraint. Here is the sql:
  ```
  CREATE TABLE cctest (ctype text);
  ALTER TABLE public.cctest  ADD CONSTRAINT cctest_ctype_cc CHECK (ctype IN ('street', 'road', 'place'));
  ```

### Potential Issues? 
* DB has 1 **domain**, (`public.year`) which is not shown anywhere 
  * the column `release_year `in table `film `does show correct definition of `year`
* DB has 1 **enum** type (`public.mpaa_rating`) which is not shown anywhere
  * the column `rating `in table `film `does show correct definition of `mpaa_rating`
* Certain type show their "raw" type value
  *  for example `smallint `shows as` int2`, `integer `as `int4 `and so on. The SQL used to define the table did not use raw types.
  * another example,` text[]` (text array) type shows up as `_text` and `character `shows up as `bpchar`
* Diagrams are showing column "size" which in certain cases does not make sense (e.g. i`nt2[5]` or `_text[2147483647]`)

### Improvements ("nice to have")
* Triggers are not shown
* Indexes are missing structure type (e.g. BTREE, GIST, GIN, etc, etc) 

Regards
Z

**Comment by npetzall** [comment]
Hi, Which version of the jdbc driver are you using?

**Comment by zam6ak** [comment]
Hi @npetzall - I am using `postgresql-42.2.4.jar` from: https://jdbc.postgresql.org/download/postgresql-42.2.4.jar

Main page is here: https://jdbc.postgresql.org/download.html

**Comment by npetzall** [comment]
The version of jdbc driver probably doesn't have anything to do with main issue but it might effect the potential issues and I've been burned before with using different driver version.

**Comment by npetzall** [comment]
I'm not at my usual computer so bare with me. This will eventually get into master and snapshot and later 6.0.1 after I've tested and verified.

`selectRoutinesSql=select routine_name, routine_type, dtd_identifier, routine_body, routine_definition, sql_data_access, security_type, is_deterministic, obj_description(routine_name::oid, routine_catalog) as routine_comment from information_schema.routines where routine_catalog = :catalog and routine_schema = :schema`

`selectRoutineParametersSql=select specific_name, parameter_name, dtd_identifier, parameter_mode from information_schema.parameters where specific_catalog = :catalog and specific_schema = :schema`

`selectCheckConstraintsSql=select tc.table_name as , tc.constraint_name, cc.check_clause as text from information_schema.check_constraints cc left join information_schema.table_constraint tc on tc.constraint_catalog = cc.constraint_catalog and tc.constraint_schema = cc.constraint_schema and tc.constraint_name = cc.constraint_name where cc.constraint_catalog = :catalog and cc.constraint_schema = :schema`

This should be it. Now just need to get to my real computer that actually can do stuff.

**Comment by npetzall** [comment]
As for domain and enum I wonder if they will be reported as UDTs, there is another issue #389 thats probably related to that as a feature improvement.

The report currently doesn't include UDT but it might be a good enhancement.

**Comment by zam6ak** [comment]
@npetzall thanks for looking into this.
I am hoping these changes make it into next release soon, so I can at least use schemaspy for documentation.

One thing I noticed though is that , in PostgreSQL, information_schema does not always offer same level of detail as system catalogs. For example, function types (normal vs aggregate vs trigger vs procedure) do not show up with the query you mentioned above.

If you use [psql](https://www.postgresql.org/docs/current/static/app-psql.html) tool you can use metatada switches to query system tables and if you set appropriate logging (see `log_min_duration_statement` config param), you will see which queries the tool actually executes (if that helps)...

Here are queries that \df and \df+  produce (information about "routines")

```sql
-- \df
SELECT n.nspname as "Schema",
  p.proname as "Name",
  pg_catalog.pg_get_function_result(p.oid) as "Result data type",
  pg_catalog.pg_get_function_arguments(p.oid) as "Argument data types",
 CASE
  WHEN p.proisagg THEN 'agg'
  WHEN p.proiswindow THEN 'window'
  WHEN p.prorettype = 'pg_catalog.trigger'::pg_catalog.regtype THEN 'trigger'
  ELSE 'normal'
 END as "Type"
FROM pg_catalog.pg_proc p
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE pg_catalog.pg_function_is_visible(p.oid)
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
ORDER BY 1, 2, 4;
```


```sql
-- \df+
SELECT n.nspname as "Schema",
  p.proname as "Name",
  pg_catalog.pg_get_function_result(p.oid) as "Result data type",
  pg_catalog.pg_get_function_arguments(p.oid) as "Argument data types",
 CASE
  WHEN p.proisagg THEN 'agg'
  WHEN p.proiswindow THEN 'window'
  WHEN p.prorettype = 'pg_catalog.trigger'::pg_catalog.regtype THEN 'trigger'
  ELSE 'normal'
 END as "Type",
 CASE
  WHEN p.provolatile = 'i' THEN 'immutable'
  WHEN p.provolatile = 's' THEN 'stable'
  WHEN p.provolatile = 'v' THEN 'volatile'
 END as "Volatility",
 CASE
  WHEN p.proparallel = 'r' THEN 'restricted'
  WHEN p.proparallel = 's' THEN 'safe'
  WHEN p.proparallel = 'u' THEN 'unsafe'
 END as "Parallel",
 pg_catalog.pg_get_userbyid(p.proowner) as "Owner",
 CASE WHEN prosecdef THEN 'definer' ELSE 'invoker' END AS "Security",
 pg_catalog.array_to_string(p.proacl, E'\n') AS "Access privileges",
 l.lanname as "Language",
 p.prosrc as "Source code",
 pg_catalog.obj_description(p.oid, 'pg_proc') as "Description"
FROM pg_catalog.pg_proc p
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
     LEFT JOIN pg_catalog.pg_language l ON l.oid = p.prolang
WHERE pg_catalog.pg_function_is_visible(p.oid)
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
ORDER BY 1, 2, 4;
```
Of course, UDTs (including enums) can be traced the same way using `\dT` and `\dT+` and domains with `\dD` and `dD+`...
Also, I do understand that using `information_schema` may be more "portable" and more standards based, even though it may be lacking some useful information.

Again, hope this helps....

**Comment by npetzall** [comment]
The big issue is really Schemaspy doesn't offer the same details as the dbms. Since we support multiple databases and the idea from the beginning was to use jdbc it would only offer what could be retrieved with jdbc. However this has changed.

So think common denominator and not too much fuzz, if we customize more we might just become a query browser with html output. (it's a lot of work maintaining multiple dbms). 

And the ER is the bread and butter I would say and table content understanding.

**Comment by npetzall** [comment]
I was about to finish it up earlier today, but my wife wanted the kids to play with me instead so I did. I did a cpl of tries using built in functions but saw that they differ between versions so im hoping using system tables, views and joins that it will work with earlier versions too.

**Comment by zam6ak** [comment]
If `information_schema` offers stability across version you need then by all means use that.
Right now, I am just looking at having routines and check constraints show up....

**Comment by npetzall** [comment]
Hopefully the two main issues are solved in PR #396 so give it a cpl of minutes and snapshot should be updated so you can give it a try. Please let me know if there are any issue. I'm gonna go over the potential issue and possibly create separate issues for them.

**Comment by npetzall** [comment]
https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.1-SNAPSHOT.jar

**Comment by npetzall** [comment]
I'll fix readme

**Comment by zam6ak** [comment]
Thanks @npetzall 
Here is some notes when testing with 6.0.1-SNAPSHOT

Routines
* Return type is missing
* Routines that use `LANGUAGE SQL` show "**SQL**", but those that use `LANGUAGE plpgsql` show "**EXTERNAL**" as language type?
* Routine's volatility does not show (VOLATILE vs STABLE vs IMMUTABLE) 
  * Not sure if this is PG specific (and if so it would fall under "nice to have" category) or if it needs to be reported under "Deterministic" 
* It shows 2 routines "_group_concat" and "group_concat" but the 2nd one is not a routine - it is an `Aggregate` that uses `_group_concat`  function as an implementation? Then, the view `actor_info` uses the aggregate in its defining SQL.
  
Check Constraints
* all columns that have NOT NULL are reported as check constraints ?
  if they are to be displayed (which is IMHO too much info because you can see it at table level), they should be in different category (e.g. NOT NULL Contraints)
  

Routines Improvements (may be PG specific but reporting here for posterity)
* No info on parallel safety (functions marked as PARALEL SAFE)
* No info on security restriction (function marked as SECURITY DEFINER, e.g.  public.rewards_report())

**Comment by npetzall** [comment]
For my 4, We actually already have a type and it's the type returned by DBMS and from the information_schema.routines 

routine_type | character_data | Always FUNCTION (In the future there might be other types of routines.)
-- | -- | --

So might want to join and use data from another table or other field from routines.

**Comment by npetzall** [comment]
Yeah I got a few minutes, security type is extracted but not presented. So needs to be added, was thinking of a case using the present join to set function or aggregate.

Yepp, saw both of them, which one do you prefer data_type or type_udt_name.

Query can be altered without effecting other dbms, so no biggie, adding more columns effect the others. Just to keep in mind, new columns more work won't be fixed tonight.

**Comment by zam6ak** [comment]
They are equally bad choices IMHO :(
It seems that the table simply does not have info to construct proper return value (e.g. `RETURNS SET OF integer` or `ARRAY`)
But it does seem that `type_udt_name` is closer to what columns in tables are using for values.....

**Comment by npetzall** [comment]
There is a possibility to create a new databaseType like pgsql10 and use tables, views or functions that are new in version 10. I would like to avoid adding a dictionary, but that is also an option.

**Comment by npetzall** [comment]
Like `pg_get_function_result`

**Comment by zam6ak** [comment]
I agree, whatever can be fixed should be portable across all DBMS

**Comment by npetzall** [comment]
So field requirement for routines:
ʼselect routine_name, routine_type, dtd_identifier, routine_body, routine_definition, sql_data_access, security_type, is deterministic, routine_comment from`
The dtd_identifier I'm probably gonna rename to return_type

For routine parameters:
ʼselect specific_name, parameter_name, dtd_identifier, p.parameter_mode fromʼ

**Comment by npetzall** [comment]
So to add some context, because you can help me with the query.
Result in query is mapped as follows for Routines:
routine_name -> routineName
routine_type -> routineType
dtd_identifier -> returnType (returnType would be more descriptive than dtd_identifier)
routine_body -> definitionLanguage (definitionLanguage better than routine_body)
routine_definition -> definition
sql_data_access -> dataAccess
security_type -> securityType
is_deterministic -> deterministic
routine_comment -> comment

And for Routines parameters:
specific_name -> routineName (dependening on dbms this might differ and we use this to find the routine, so must be the routine_name from the routines sql above)
parameter_name -> paramName
dtd_identifier -> type (data_type)
parameter_mode -> mode (should be in, out or inout)

I realized I can't change these until 7.0.0 since it would be a breaking change. So I'll create a issue for that and label it 7.0.0.

**Comment by npetzall** [comment]
@zam6ak Security restriction is that a front page (routines.html) or the specific routines page information?

**Comment by npetzall** [comment]
So I've come up with this so far for routines:
`select r.routine_name, r.routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema';`

routine_name|routine_type|dtd_identifier|routine_body|routine_definition|sql_data_access|security_type|is_deterministic|routine_comment
----|----|----|----|---|---|---|---|---
_group_concat|FUNCTION|text|SQL|****|MODIFIES|INVOKER|YES|[NULL]
film_in_stock|FUNCTION|SETOF integer|SQL|****|MODIFIES|INVOKER|NO|Current stock
film_not_in_stock|FUNCTION|SETOF integer|SQL|****|MODIFIES|INVOKER|NO|[NULL]
get_customer_balance|FUNCTION|numeric|PLPGSQL|****|MODIFIES|INVOKER|NO|[NULL]
inventory_held_by_customer|FUNCTION|integer|PLPGSQL|****|MODIFIES|INVOKER|NO|[NULL]
inventory_in_stock|FUNCTION|boolean|PLPGSQL|****|MODIFIES|INVOKER|NO|[NULL]
last_day|FUNCTION|date|SQL|****|MODIFIES|INVOKER|YES|[NULL]
last_updated|FUNCTION|trigger|PLPGSQL|****|MODIFIES|INVOKER|NO|[NULL]
rewards_report|FUNCTION|SETOF customer|PLPGSQL|****|MODIFIES|DEFINER|NO|[NULL]
group_concat|FUNCTION|text|INTERNAL|****|MODIFIES|INVOKER|YES|[NULL]

I put **** as definition since it didn't play well with the markdown table.

**Comment by npetzall** [comment]
For parameters we are now at
`select r.routine_name as specific_name, coalesce(p.parameter_name, '$' || p.ordinal_position) as parameter_name, p.data_type as dtd_identifier, p.parameter_mode from information_schema.parameters p left join information_schema.routines r on r.specific_name = p.specific_name where p.specific_schema = :schema`

specific_name|parameter_name|dtd_identifier|parameter_mode
---|---|---|---
film_in_stock|p_store_id|integer|IN
film_in_stock|p_film_count|integer|OUT
film_in_stock|p_film_id|integer|IN
film_not_in_stock|p_film_count|integer|OUT
film_not_in_stock|p_film_id|integer|IN
film_not_in_stock|p_store_id|integer|IN
get_customer_balance|p_effective_date|timestamp without time zone|IN
get_customer_balance|p_customer_id|integer|IN
_group_concat|$1|text|IN
_group_concat|$2|text|IN
group_concat|$1|text|IN
inventory_held_by_customer|p_inventory_id|integer|IN
inventory_in_stock|p_inventory_id|integer|IN
last_day|$1|timestamp without time zone|IN
rewards_report|min_monthly_purchases|integer|IN
rewards_report|min_dollar_amount_purchased|numeric|IN

**Comment by npetzall** [comment]
As for check_constrints, change it to:
`select tc.table_name, tc.constraint_name, cc.check_clause as text from information_schema.check_constraints cc left join information_schema.table_constraints tc on tc.constraint_catalog = cc.constraint_catalog and tc.constraint_schema = cc.constraint_schema and tc.constraint_name = cc.constraint_name where cc.constraint_name not like '%not_null' and tc.constraint_schema = :schema`

this would filter all constraint which ends with not_null which all the generated seem to have.

**Comment by zam6ak** [comment]
It appears good but only way to know for sure is to test with other (perhaps more complex) databases....
For routines, why call column `dtd_identifier` instead of `return_value` or similar? 
Also, what would be use for `sql_data_access` ?

**Comment by npetzall** [comment]
I created #399 to change `dtd_identifier` to return_value, but actually changing other column labels at the same time. Since it's possible to create your own databaseTypes, these column labels can be considered public api and can only be changed with new major version. So it can be fixed at earliest in 7.0.0

I think that the routines are base on mysql information_schema so that's why dtd_indetifier is used.
And from mysql documentation `sql_data_access` might be useful but don't think it's in the report "yet"

>SQL_DATA_ACCESS
The data access characteristic for the routine. The value is one of CONTAINS SQL, NO SQL, READS SQL DATA, or MODIFIES SQL DATA.

**Comment by npetzall** [comment]
@zam6ak latest queries are in master, also don't forget the question. About where the invoker/define security information should be placed.

**Comment by zam6ak** [comment]
@npetzall 

> @zam6ak latest queries are in master, also don't forget the question. About where the invoker/define security information should be placed.

Is there a specific snapshot I should test or...?

> @zam6ak Security restriction is that a front page (routines.html) or the specific routines page information?

This could be on both pages but if not possible then at least on routine page

**Comment by npetzall** [comment]
Latest snapshot will do.

I'll add security_type to both and see how it looks.

**Comment by zam6ak** [comment]
@npetzall when you say latest snapshot, is that same as link you provided earlier?
https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.1-SNAPSHOT.jar

**Comment by npetzall** [comment]
Yes, if not we have an issue with the buildscript.

**Comment by npetzall** [comment]
![routines_security](https://user-images.githubusercontent.com/4175123/44370292-e0bad800-a4d9-11e8-802a-8e48645d0966.png)

Adding security restriction to routines.html (main routines page) was easy had an table and everything.
Adding it to the specific routine page feels a bit trickier since no table existed, and I got to thinking.

We could add a section called attributes and with this, we could also add a new query for attributes.
This way we could add thing that might be dbms specific like "VOLATILE vs STABLE vs IMMUTABLE" and "Parallel safe" or anything else one could come up with.

But I would like to break this out to a new issue, since it involves layout and query changes. This would fall under 6.1.x as it's added functionality to the "query api".

**Comment by zam6ak** [comment]
@npetzall the latest snapshot version looks much better - thanks.
And yes makes sense to start with new issue.

**Comment by npetzall** [comment]
@zam6ak are we good with this issue, close this and continue later on when time for 6.1 with #407?

**Comment by zam6ak** [comment]
@npetzall Sounds good - thanks for your help

**Comment by basildba** [comment]
So, where is coalesce in routine list?

**Comment by npetzall** [comment]
@basildba this is really old, I skimmed the issue, but sadly I don't actually know what you are referring to?

**Comment by basildba** [comment]
where, in which view can we find "coalesce" and its parameters?
it is not in pg_proc, nor in information_schema.routines

**Comment by npetzall** [comment]
@basioldba Well if it's not in pg_proc and not in information_schema.routines you probably shouldn't find it.
It must be a schema defined function to be visible in schemaspy. If you're referring to the built-in function you need to check the dbms documentation.
