### ISSUE TITLE
Document how to use "schemaspy/schemaspy" Docker image

### ISSUE THREAD

**Issue by harobed** [schemaspy/schemaspy#422]
Hi,

I suggest to document how to use "[schemaspy/schemaspy](https://hub.docker.com/r/schemaspy/schemaspy/)" Docker image.

I'm on OSX, and I execute:

```
$ docker run --rm --net=mynetwork schemaspy/schemaspy:latest -t mariadb -db dbname -host dbhost -port 3306 -u user -p password -s dbname
...
INFO  - View the results by opening /output/index.html
```

Question: how can I access to `/output/` directory?

Suggestion: if you remove [VOLUME /drivers /output /config](https://github.com/schemaspy/schemaspy/blob/master/Dockerfile#L49) in `schemaspy` `Dockerfile` I can use mounted volume, like that:

```
$ docker run --rm -v $(pwd)/output/:/ouptput/ --net=mynetwork schemaspy/schemaspy:latest -t mariadb -db dbname -host dbhost -port 3306 -u user -p password -s dbname
...
```

And I can get the result in `./output/` directory.

What do you think about this?

Best regards,
Stéphane

**Comment by npetzall** [comment]
The current documentation on docker hub says you need to host mount /output
Both when listing volumes and later it also present in the usage example 

So the first execution goes against the documentation. 

But it was probably 1 year since I ran it on osx things, might have changed.

Using Docker4Mac or Docker Toolbox? Toolbox is a strange since it uses VirtualBox.

**Comment by harobed** [comment]
Ok, I didn't see this typo ! `ouPtpup`.

Thanks for your help and sorry for the inconvenience.
