### ISSUE TITLE
font issue relationship (docker)

### ISSUE THREAD

**Issue by peka1** [schemaspy/schemaspy#479]
There seems to be a font issue when running schemaspy in an pre-existing docker container. It seems to concern only the image in the Relationships tab, rest looks OK.

I have installed everything from scratch in an existing docker container.
Using following versions:
docker 2.0.0.0-mac81
schemaspy 6.0.0.
graphviz 2.38.0 (it is also happening with viz.js)
jre 1.8.0_191
postgresql-9.4.1212
postgres database

## Expected Behavior
Text should appear in Table boxes instead of empty squares

## Current Behavior
There is no text in the generated Relationships:
![image](https://user-images.githubusercontent.com/45835145/49906228-e95c6300-fe68-11e8-9827-463a9739140f.png)

## Steps to Reproduce (for bugs)
in existing docker container
1. download schemaspy
2. install graphviz (conda install graphviz)
3. download and install jre (jre-8u191-linux-x64.tar.gz)
4. download and install jdbc (postgresql-9.4.1212.jar)
5. run schemaspy connecting to existing postgres db

java -jar schemaspy-6.0.0.jar -t pgsql -db rate_db -host 127.0.0.1:5432 -u postgres  -dp postgresql-9.4.1212.jar -s public -noads -o ./schema_rate_db

## Context

* Database type (e.g. MySQL): postgres
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* Version used: 6.0.0
* Environment name and version (e.g. Chrome 39): Docker
* Operating System and version (e.g. Windows 10): linux
* Java version: 1.8.0_191

Thanks for your support,
Petr

**Comment by npetzall** [comment]
Hi @peka1 

I think this a charset/codepage issue.

We have a prebuilt docker image that you can use. I can't guarantee that it will work better but if you have issues with our container we will fixit.

If same issue with viz.js are you referring to the `-vizjs`argument you must use SchemaSpy-6.1.0-SNAPSHOT or newer.

Option -noads doesn't exist. Don't know why people are using it....

The container that you are building which image is it base on, so that I can check locale settings.

(I'm GMT+1 and will be available from around 10 PM//22:00 after kids have gone to bed and am available on gitter, link in readme.md)

**Comment by npetzall** [comment]
Our Docker contains postgreSQL jdbc driver 42.1.1 latest is 42.2.5 but can be overrided by host mounting your own driver.

**Comment by peka1** [comment]
Hi Nils,

thanks for your response. 

Happy to report that **using the 6.1.0-SNAPSHOT version together with the -vizjs parameter has resolved the issue**.

Best regards,
Petr

**Comment by npetzall** [comment]
@peka1 Using 6.1.0-SNAPSHOT without -vizjs did it still produce the incorrect output?

**Comment by peka1** [comment]
yes, it doesn't work correctly w/o the -vizjs option.

**Comment by npetzall** [comment]
Since I'm missing information about the container that you have used. I'm gonna assume that it has to do with fonts. Either font-config or that the system is missing a font that is used.
