### ISSUE TITLE
Couldn't get full db document 

### ISSUE THREAD

**Issue by sunilsql** [schemaspy/schemaspy#499]
Result I got- Just  some tables and columns. MIssing tables, relationships, constraints everting :(
* Database type : MSSQL 2017
* Full command including arguments how you run SchemaSpy:
java -jar schemaspy-6.0.0.jar -t mssql05-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -u test -p test -s dbo -o E:\

Error-

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESKTOP-SM37531 with PID 14096 (E:\schemaspy-6.0.0.jar started by sunil in E:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.615 seconds (JVM running for 2.184)
INFO  - Configuration file not found
INFO  - Starting schema analysis

WARN  - Failed to query Graphviz graphvizVersion information
WARN  -   with: dot -V
WARN  -   {}
INFO  - Graphviz query failure details:
INFO  - Connected to Microsoft SQL Server - 13.00.4224
INFO  - Gathering schema details
Gathering schema details......(0sec)
Connecting relationships......(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
.INFO  - Using external StyleSheet file: schemaSpy.css
.
Warning: Failed to run dot.
   Download dot graphvizVersion 2.26 or versions greater than 2.31
   from www.graphviz.org and make sure that dot is either in your path
   or point to where you installed Graphviz with the -gv option.
   Generated pages will not contain a diagramtic view of table relationships.
......(1sec)
Writing/diagramming detailsINFO  - Completed summary in 1 seconds
INFO  - Writing/diagramming details
...(0sec)
Wrote relationship details of 3 tables/views to directory 'E:\' in 2 seconds.
View the results by opening E:\index.html
INFO  - Wrote table details in 0 seconds
INFO  - Wrote relationship details of 3 tables/views to directory 'E:\' in 2 seconds.
INFO  - View the results by opening E:\index.html

## Your Environment

* Version used: schemaspy6.0.0
JTDS 3.0,  Graphviz2.38
server: MSSQL 2017
Windows: 10

**Comment by npetzall** [comment]
Missing columns is strange for tables and routines it might be that the database contains multiple schemas.

Could you verify that all expected tables reside in the dbo schema.

Relationships requires graphviz. 

If you download 6.1.0-SNAPSHOT there is a new option `-vizjs` that will use a javascript instead of the graphviz executable (dot).

**Comment by sunilsql** [comment]
I have changed the schema and now it's working looking great. How can I
escape from " Configuration file not found". Is it an error?

Can we pass multiple schemas and databases?

I am new to SchemaSpy sorry for giving a hard time.

**Comment by npetzall** [comment]
Configuration file not found is not an error, but I'm gonna treat the question as something to improve.

Multiple schemas is/should be supported. I don't have the argument in my head, but should be noted in the docs.

Multiple databases I'm a bit unsure about since, different dbms look at it differently but mainly is limited by how the connectionstring is written for jdbc. 

There is a request for adding database selection or having alla queries be fully qualified with catalog.schema.table

But as I said, it's a bit vendor and driver specific.

**Comment by sunilsql** [comment]
Please leave a comment sharing URL(Doc) for using multiple Schema and regarding multiple DB if you can. As I want to schedule a weekly job on some databases.

Scared about Configuration file not found, hope it will fix soon.

Very useful 

Thanks for your time :)

**Comment by npetzall** [comment]
https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#processing

You have both schemas and all.

The report will look a bit different. 

The configuration file not found is if you want to us a configuration file instead of arguments on the command line. 

The change will be to write when one is found and no output when missing. 

For multiple databases I'm guessing a batch script will be the only solution for now.

**Comment by sunilsql** [comment]
I will look into it.

Thank you
