### ISSUE TITLE
"-all" gather and analyze multiple database schemas at ones into one output

### ISSUE THREAD

**Issue by Kamyabnz** [schemaspy/schemaspy#587]
I have a question concerning implementing '-noschema' on my personal project for an Informix DB.  I wanted to look through how it was implemented before but the current code works differently then before. Is it even possible to implement such Argument that gets all Informix DB Catalogs and puts them into one Analyzed output ? 

Because i am working with many Catalogs and it would be impossible to look through them after 200 Catalogs on Multi.HTML and it doesn't make sense in my circumstances. I am looking through the code and it takes the -all or -schamas string and does the data gathering and analyzing + page generation for every single one Schema from scratch when it is done with one.

Do you have any suggestions where i can start changing the Gathering and Analyzing system, where i could analyze all schemas at ones + generation, where multi.page contains just one option "all-schemas" something like that.

**Comment by npetzall** [comment]
I'm not sure I understand what you want to accomplish.

But then again I'm not a Informix DBA.

Yepp, a long time a go it spawn a new schemaspy process for each schema, unsure if they were executed in parallel or sequential. But that was moved to be done in the same process when this repo was created.

I most cases a schema is an isolated container so it sort of needs to do it from scratch to not pollute other schema and the fact that schemas can contain identically named tables that have different structure and content.

I actually removed `-noschema` a while back since there was no code using the argument.

But if we circle back to you question and what you might want to accomplish.

You want [catalog].[schema].[table] to be merge even when they have different schemas as an example.

cat_a.schema_a.table_a should be merged/overlapped/considered the same as cat_a.schema_b.table_a?

Or does it extend an include catalog also?

`-all` just gives you a index-page in the report.

I've created #204 as a feature to refactor the model and actually be able to work with the dbms as a whole instead of database = schema, which might be the "from scratch" that you refer to.

**Comment by Kamyabnz** [comment]
Firstly thank you for your reply.

At the end of the day, I want all of the schemas = catalogs in Informix to be in just one relationship page, tables page, columns page, and have to them all in one output. So I wanted to remove the index-page with the multiple schemas. 

About the example, you have given, I have already created procedures to compare the tables from different schemas and get around the same table names and so on but it was used in the older version of SchemaSpy and because multiple schemas are now differently handled I wanted to see if I can bring back the function for SchemaSpy to generate just ones. 

The files sizes have also gotten a lot bigger than in the old version, because of the new layout system, where bower and all of the front -end is copied every single time for each schema.

So in one sentence, I want to have all of the schemas tables, relationships and so on in one output.

**Comment by Kamyabnz** [comment]
@npetzall I looked through the related issues and I had the problem at first to run SchemaSpy with Informix database. I couldn't get it running with -noschemas because it is not used anymore, could not get all of the catalog tables with -s Informix and also by specifying it still thinks it supports Schemas #219 

I want only one output without the index-page where it contains all of my catalogs(Schemas).

**Comment by Kamyabnz** [comment]
I have solved the problem by changing the steps in SchemaAnalyzer.java on my part, this was just a Solution for my Project. 

Here is the commit on my Forked Repo (Just for you to see the changes better):

b42483c65587c83cff297bbf642ec0d5388a58cf

That is why i am closing this issue.
