### ISSUE TITLE
PostgreSQL Polymorphic Function Documentation broken

### ISSUE THREAD

**Issue by albrechtd** [schemaspy/schemaspy#621]
If a (PostgreSQL) schema contains polymorphic functions, i.e. two or more functions with the same name, but different arguments, the output is broken.

E.g. the following PostgreSQL code

```
CREATE FUNCTION public.foo(_val text) RETURNS bigint
    LANGUAGE sql
    AS $$
SELECT COUNT(*) FROM testdata WHERE value = _val
$$;

CREATE FUNCTION public.foo(_id bigint, _val text) RETURNS bigint
    LANGUAGE sql
    AS $$
SELECT COUNT(*) FROM testdata WHERE id = _id AND value = _val
$$;
```
produces the following output: ![polymorphic_function](https://user-images.githubusercontent.com/22217289/67895574-0cfcca80-fb5b-11e9-82ea-a431168bf091.png)

The effect is reproducible with v6.1.0 and a PostgreSQL 10 database schema.

**Comment by npetzall** [comment]
Hi could you provide a script to recreate this? Would save me some time.

**Comment by albrechtd** [comment]
> Hi could you provide a script to recreate this? Would save me some time.
> 
> Update: You did, my bad.

I attach my test schema ([test.zip](https://github.com/schemaspy/schemaspy/files/3795331/test.zip) which I also used to trigger issue #620).  Just say `psql postgres < test.sql`…

Thanks a lot for looking into this one - I use polymorphism frequently, so this is a real blocker for me.

As a side-effect, the “Routines” overview will need an additional column with the parameters as to distinguish between the different function, btw.

**Comment by npetzall** [comment]
Is it possible to have this kind of overloading

```
CREATE FUNCTION public.foo(_val text) RETURNS bigint
    LANGUAGE sql
    AS $$
SELECT COUNT(*) FROM testdata WHERE value = _val
$$;

CREATE FUNCTION public.foo(_id bigint, _val text) RETURNS bigint
    LANGUAGE sql
    AS $$
SELECT COUNT(*) FROM testdata WHERE id = _id AND value = _val
$$;

CREATE FUNCTION public.foo(_id bigint, _val bigint) RETURNS bigint
    LANGUAGE sql
    AS $$
SELECT COUNT(*) FROM testdata WHERE id = _id AND value_int = _val
$$;
```

**Comment by npetzall** [comment]
I checked a mysql, pgsq, sqlserver and they all have a specific_routine_name, which should make it possible to handle overloading. But as you say, this needs to be shown in the first view. This however not used in our code, so a small code change and I think I can make it backwards compatible. Then a web update which should be totally fine.

Now I just need some time.

**Comment by npetzall** [comment]
I just finished routines for Informix and it has overloaded(procedures/functions) there are some issue with how SchemaSpy handles rutines. This will change in 7.0 since it's needed. but as a workaround for Informix i changed the procedure/function name to it's signature.

I'm gonna see the same workaround can be applied to pgsql.

This would only be a SQL query change and result in routine names with signature like:
`foo(text)` and
`foo(bigint,text)`

**Comment by albrechtd** [comment]
> This would only be a SQL query change and result in routine names with signature like:
> `foo(text)` and
> `foo(bigint,text)`

This solution would be absolutely perfect IMHO!  Please let me know if there is anything I could/should test with PostgreSQL!

Thanks, Albrecht.

**Comment by npetzall** [comment]
Just need to fix #654 first then I can take a stab at this. I have a really simple solution in mind.

**Comment by npetzall** [comment]
I have constructed two queries that should work. I'm just gonna see how far back they work.
They use what must be an undocumented function, also need to verify the datatype of the column in older versions. We have a databaseType without version so I might need to create a pgsql9 or pgsql10.

**Comment by albrechtd** [comment]
I today tried the 6.1.1-SNAPSHOT version with my database running on PostgreSQL 11, and the result looks perfect!  Thanks a lot for your great work!  Best, Albrecht.

**Comment by albrechtd** [comment]
Just a dumb question – how do you calculate the names of the table html pages, e.g. `get_next_task_bigint__a58579a.html`?  It looks as if you append the parameter(s) (just `bigint` in this case), but how do you calculate the 7 or 8 chars hex value (`a58579a`)?  Is it a fixed value, i.e. can I hard-code it in cross-references in comments, or may it change, i.e. should I calculate it in a script myself?

Thanks, Albrecht.

**Comment by npetzall** [comment]
Not a dumb question at all. But sadly nothing I can check at the moment. But there is some kind of support for linking in comments, so need to check if that has been updated to reflect my changes.

The filename is at most 40 chars(excluding extension) so we put as much as possible and room for the has of the text field.

So the linking function should maybe be updated to handle this, so that you would write the reported name in schemaspy and schemaspy would encode it to match the filename. 

I can double check if the hashing would change between runs, but I don't think so. Just because my tests work on every run.

**Comment by albrechtd** [comment]
Thanks a lot for the clarification!  I usually add Markdown links `[routine name](relative routine url)` to my comments, and let a script tweak the relative paths.  So this should be fine for me!
