### ISSUE TITLE
SchemaSpy for Informix does not show check constraints

### ISSUE THREAD

**Issue by begooden-it** [schemaspy/schemaspy#637]
## Expected Behavior
I love schemaspy and we are using it intensively in our open source project www.kandooerp.org , for now on Informix, maybe later on PostGresql.

With Nils help, we could integrate table comments and columns comments and this works great.
Now the community is using schemaSpy data, and we just realized that CHECK CONSTRAINTS are missing.
We would definitely like to see CHECK constraints listed in the html pages

## Current Behavior
Check constrains are not listed

## Possible Solution
Obtaining the global  constraints list can be obtained with the following query
select t.tabname,c.constrname,k.checktext,k.seqno
from sysconstraints c,syschecks k,systables t
where c.constrid = k.constrid
and c.tabid = t.tabid
and c.constrtype = 'C'
and k.type = 'T' ;

OR table by table
select t.tabname,c.constrname,k.checktext,k.seqno
from sysconstraints c,syschecks k,systables t
where c.constrid = k.constrid
and c.tabid = t.tabid
and c.constrtype = 'C'
and k.type = 'T'
and t.tabname = "my table name"

## Context

* Database type informix, don't know about postGresql
* Database driver version any
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* Version used: schemaspy-6.1.0-SNAPSHOT.jar

* Environment name and version (e.g. Chrome 39):
* Centos 7,8, windows 10
* Java version:openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Comment by npetzall** [comment]
Schemaspy only list check constraints as 3 columns. (need to update documentation I have only written down two).
table_name, constraint_name and text  

and it only does one query.

I know from #594 that Informix might split data over multiple rows. Which isn't handled by schemaspy. But could possibly be implemented by having a append flag for the DBMS, so that we allow appending "text/data" for certain columns that might have been split over multiple rows.

(the k.seqno, tells me that it might be split, the append would work if we sorted k.seqno)
