### ISSUE TITLE
Informix missing routines

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#648]
Routines are missing for Informix.

Routine definition spans multiple rows, just like check constrains #637 

So this is dependent on #637 and the append feature needed.

Then when need the custom queries.

**Comment by npetzall** [comment]
Need to add append functionally like in #637 but for routines.

Queries needed:
```
selectRoutinesSql=
    Fetch routines, expected columns:
    routine_name, routine_type, dtd_identifier, routine_body, routine_definition,sql_data_access, 
    security_type, is_deterministic, routine_comment
selectRoutineParametersSql=
    Fetch parameters for routines, expected columns:
    specific_name, parameter_name, dtd_identifier, parameter_mode
```

#594 should be able to aid with the queries.

**Comment by begooden-it** [comment]
Hi Nils





Sorry I am a bit overload here, thus my reaction time



I know you are going to kill me but again what is the url of the snapshot?
Can’t find it in my email history



Thanks



Eric

*De :* Nils Petzäll <notifications@github.com>
*Envoyé :* vendredi 6 mars 2020 01:01
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



@begooden-it <https://github.com/begooden-it> @Kamyabnz
<https://github.com/Kamyabnz> can you have look and test the most recent
snapshot that should be built within minutes.

It should now contain both CheckConstraint and Routines.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TBI2ZICEPW5FXK3L3LRGA4MRA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN7JHJA#issuecomment-595497892>,
or unsubscribe

**Comment by npetzall** [comment]
@begooden-it no worries, I've been busy myself. 
link -> [latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.1.1-SNAPSHOT.jar)

I'm just happy that you're willing to take the time to help improve SchemaSpy.

**Comment by Kamyabnz** [comment]
@npetzall I will do that in one hour, in Germany it was 1:00at night 😅

Hopefully it works out

**Comment by begooden-it** [comment]
Almost there …



Getting this exception



.....ERROR - IOException

/home/www/kandoodb/routines/metadata_2(out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out varchar,out integer,out integer,out
integer,out integer,out varchar,out varchar,out varchar,out varchar,out
varchar,out varchar,out varchar,out varchar,out varchar,out varchar,out
varchar,out integer,out integer,out integer,out integer,out integer,out
integer).html: File name too long

INFO  - StackTraces have been omitted, use `-debug` when executing
SchemaSpy to see them



Will relaunch with debug

now



*De :* Kamyab Nazari <notifications@github.com>
*Envoyé :* vendredi 6 mars 2020 08:34
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



@npetzall <https://github.com/npetzall> I will do that in one hour, in
Germany it was 1:00at night 😅

Hopefully it works out

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TBEZCAXD3R3HTYWXMLRGCRPJA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOAMCTQ#issuecomment-595640654>,
or unsubscribe

**Comment by begooden-it** [comment]
Here is the result with the debug option



ERROR - dot -Tpng:cairo mbparms.1degree.dot -ombparms.1degree.png -Tcmapx:
in label of node mbparms

( got tons of this error but does not seem to have influence)



.....ERROR - IOException

java.nio.file.FileSystemException:
/home/www/kandoodb/routines/metadata_2(out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out varchar,out integer,out integer,out
integer,out integer,out varchar,out varchar,out varchar,out varchar,out
varchar,out varchar,out varchar,out varchar,out varchar,out varchar,out
varchar,out integer,out integer,out integer,out integer,out integer,out
integer).html: File name too long

        at
sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)

        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)

        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)

        at
sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)

        at
java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)

        at java.nio.file.Files.newOutputStream(Files.java:216)

        at java.nio.file.Files.newBufferedWriter(Files.java:2860)

        at org.schemaspy.util.Writers.newPrintWriter(Writers.java:33)

        at
org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:411)

        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)

        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)

        at
org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)

        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)

        at org.schemaspy.Main.main(Main.java:55)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)

        at
org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)



*De :* Kamyab Nazari <notifications@github.com>
*Envoyé :* vendredi 6 mars 2020 08:34
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



@npetzall <https://github.com/npetzall> I will do that in one hour, in
Germany it was 1:00at night 😅

Hopefully it works out

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TBEZCAXD3R3HTYWXMLRGCRPJA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOAMCTQ#issuecomment-595640654>,
or unsubscribe

**Comment by Kamyabnz** [comment]
I am baffled, which part of the process do you get this error and what is already created ?

**Comment by begooden-it** [comment]
After this section ( adding foreign key constraints “Implied constraint’

DEBUG - Adding foreign key constraint 'Implied Constraint' to
kandoodb.informix.warehouse

DEBUG - Adding foreign key constraint 'Implied Constraint' to
kandoodb.informix.warehouse



I have tons of the following ( which I always had, does not seem to have
impact though)

ERROR - dot -Tpng:cairo relationships.implied.compact.dot
-orelationships.implied.compact.png -Tcmapx: Warning: cell size too small
for content

ERROR - dot -Tpng:cairo relationships.implied.compact.dot
-orelationships.implied.compact.png -Tcmapx: in label of node account



Then I have this message

End of the ‘tons of’

ERROR - dot -Tpng:cairo mbparms.1degree.dot -ombparms.1degree.png -Tcmapx:
Warning: cell size too small for content

ERROR - dot -Tpng:cairo mbparms.1degree.dot -ombparms.1degree.png -Tcmapx:
in label of node mbparms

.....ERROR - IOException

java.nio.file.FileSystemException:
/home/www/kandoodb/routines/metadata_2(out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out integer,out integer,out integer,out
integer,out integer,out integer,out varchar,out integer,out integer,out
integer,out integer,out varchar,out varchar,out varchar,out varchar,out
varchar,out varchar,out varchar,out varchar,out varchar,out varchar,out
varchar,out integer,out integer,out integer,out integer,out integer,out
integer).html: File name too long

        at
sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)

        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)

        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)

        at
sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)

        at
java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)

        at java.nio.file.Files.newOutputStream(Files.java:216)

        at java.nio.file.Files.newBufferedWriter(Files.java:2860)

        at org.schemaspy.util.Writers.newPrintWriter(Writers.java:33)

        at
org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:411)

        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)

        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)

        at
org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)

        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)

        at org.schemaspy.Main.main(Main.java:55)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)

        at
org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)





File name too long might be related to my specific data schema, couldn’t it?





*De :* Kamyab Nazari <notifications@github.com>
*Envoyé :* vendredi 6 mars 2020 08:53
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



I am baffled, which part of the process do you get this error and what is
already created ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TG6GA4UF4UDRVXQDC3RGCTXPA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOANRYI#issuecomment-595646689>,
or unsubscribe

**Comment by npetzall** [comment]
I know what the problem is, I'll create a fix for it.

Since I add input arguments to the routine name, and the routine name will be the filename it will create files that have names that are too long for the filesystem.

**Comment by begooden-it** [comment]
Is this nostalgy of the time when file names were limited to 8 chars 😉



I like long SIGNIFICANT names, but sometimes this gets totally exaggerate

Please ping me when the fix is available



Cheers

Eric



*De :* Nils Petzäll <notifications@github.com>
*Envoyé :* vendredi 6 mars 2020 09:01
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



I know what the problem is, I'll create a fix for it.

Since I add input arguments to the routine name, and the routine name will
be the filename it will create files that have names that are too long for
the filesystem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TDJFCPONS2DPVDF74TRGCUTHA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOAOEQI#issuecomment-595649089>,
or unsubscribe

**Comment by Kamyabnz** [comment]
Yea Ping me to, getting the same error while testing, interessted in what solution you will implement.

**Comment by npetzall** [comment]
@begooden-it @Kamyabnz I've implemented a simple fix. Should like normal be available in a cpl of minutes. If it doesn't work for you. Please re-open #654 and some info, so I can try to really fix it.

**Comment by begooden-it** [comment]
Hi Nils,





Is it available as the snapshot ?



Thanks





*De :* Nils Petzäll <notifications@github.com>
*Envoyé :* vendredi 6 mars 2020 23:41
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



@begooden-it <https://github.com/begooden-it> @Kamyabnz
<https://github.com/Kamyabnz> I've implemented a simple fix. Should like
normal be available in a cpl of minutes. If it doesn't work for you. Please
re-open #654 <https://github.com/schemaspy/schemaspy/issues/654> and some
info, so I can try to really fix it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TCUGWBAJZKPPC7527LRGF3WXA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEODCUWY#issuecomment-595995227>,
or unsubscribe

**Comment by npetzall** [comment]
Yes same link as before.

**Comment by begooden-it** [comment]
Just tested !







It worked fine for me!



I can see we also have the routines!



great job guys!



Thank you





*De :* Nils Petzäll <notifications@github.com>
*Envoyé :* samedi 7 mars 2020 09:26
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



Yes same link as before.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74TFL3MKDUSGWOVKHATDRGIAKXA5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEODSY3Q#issuecomment-596061294>,
or unsubscribe

**Comment by npetzall** [comment]
@begooden-it @Kamyabnz if you have any idea of how we can exclude system defined routines that would be nice, since it creates a lot of noise.

**Comment by begooden-it** [comment]
Hi Nils,





It creates a lot of noise, but it is at the same time very instructive: I
just discovered bunches of useful Functions and procedures. I’ll take a
look, if not consusive, I’ll someone in the R&D.



If there is a distinction criteria, I would go for an option to include the
system funcs or not



Give me some time

I



*De :* Nils Petzäll <notifications@github.com>
*Envoyé :* samedi 7 mars 2020 10:22
*À :* schemaspy/schemaspy <schemaspy@noreply.github.com>
*Cc :* begooden-it <eric.vercelletto@begooden-it.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [schemaspy/schemaspy] Informix missing routines (#648)



@begooden-it <https://github.com/begooden-it> @Kamyabnz
<https://github.com/Kamyabnz> if you have any idea of how we can exclude
system defined routines that would be nice, since it creates a lot of noise.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schemaspy/schemaspy/issues/648?email_source=notifications&email_token=AEO74THUGBTGHP6AAHUWZFLRGIGZ7A5CNFSM4K7IUB32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEODUAJY#issuecomment-596066343>,
or unsubscribe

**Comment by Kamyabnz** [comment]
This all awesome, i will try to also look into it

**Comment by npetzall** [comment]
I'll think of something smart for 7.0 we could have both but it would be nice with a flag so that it can be sorted so that user defined are grouped together either in the beginning or the end.
