### ISSUE TITLE
tables with partitions were not included (Postgres)

### ISSUE THREAD

**Issue by wcj365** [schemaspy/schemaspy#717]
My Postgres database has tables that are partitioned. For example, a table "claims" is partitioned into claims_2016, claims_2017, claims_2018.
When generated the documentation, only claims_2016, claims_2017, claims_2018 are included. Claims table is not included. I tried  option   -i "Claims|table_x||table_y" to inlcude Claims table, it still does not generate documentation for Claims table.
I am running Schemaspy 6.1.0 on Centos 7 and open JDK 1.8.0 and use postgres-42.2.14.jar.
Thanks!

**Comment by npetzall** [comment]
I suspect that the "claims" table is of a different type. Which version of pgsql are you using?

**Comment by npetzall** [comment]
Same solution as in #712 but replace `FOREIGN TABLE` with `PARTITIONED TABLE`

**Comment by wcj365** [comment]
PostgreSQL 12.3

**Comment by wcj365** [comment]
> Same solution as in #712 but replace `FOREIGN TABLE` with `PARTITIONED TABLE`

I tried this approach but the problem remains.

**Comment by npetzall** [comment]
Just wanted to bring you an update. I was testing and it was working for me directly. I noticed I was using PGSQL 10.4 and not 12 so switched to 12. Still worked without any changes. I thought I was using the same driver, but apparently I was using 42.2.4 and not 42.2.14 after that switch I now only get partitions and not the table.

I've also confirmed that the solution in #712 should work. I changed to pgsql11 since your using pgsql 12.

Create a file in the same location as the schemaspy-jar. Call it mypgsql.properties.
It should contain the following information:

```
extends=pgsql11
tableTypes=TABLE,PARTITIONED TABLE
```
Replace `-t pgsql` or `-t pgsql11` with `-t mypgsql` on the commandline or in properties file.

Lazy fix would be to switch to 42.2.4 version of the driver =)

**Comment by wcj365** [comment]
> Just wanted to bring you an update. I was testing and it was working for me directly. I noticed I was using PGSQL 10.4 and not 12 so switched to 12. Still worked without any changes. I thought I was using the same driver, but apparently I was using 42.2.4 and not 42.2.14 after that switch I now only get partitions and not the table.
> 
> I've also confirmed that the solution in #712 should work. I changed to pgsql11 since your using pgsql 12.
> 
> Create a file in the same location as the schemaspy-jar. Call it mypgsql.properties.
> It should contain the following information:
> 
> ```
> extends=pgsql11
> tableTypes=TABLE,PARTITIONED TABLE
> ```
> 
> Replace `-t pgsql` or `-t pgsql11` with `-t mypgsql` on the commandline or in properties file.
> 
> Lazy fix would be to switch to 42.2.4 version of the driver =)

Thank you so much for the thorough research, working solutions, and quick response!
I took the lazy route and it worked beautifully. Too thumbs up!
