### ISSUE TITLE
Option -vizjs in error

### ISSUE THREAD

**Issue by ivanrome** [schemaspy/schemaspy#797]
Lauching schemaspy with -vizjs argument, the analysis ends with no error but graphs are rendered as an XML error.

## Expected Behavior

Graphs with vizjs works

## Current Behavior

Any svg generated are rendered as this: 

```
Erreur d’analyse XML : mal formé
Emplacement : file:///C:/out/BOX_01/diagrams/tables/MY_TABLE.1degree.svg
Numéro de ligne 81, Colonne 119 :
<text text-anchor="start" x="275.4835" y="-46.3" font-family="Helvetica,sans-Serif" font-size="11.00" fill="#000000">3￿
----------------------------------------------------------------------------------------------------------------------^
```
Opening the MY_TABLE.1degree.svg with notepad++ I see the ling 81 that the separator spaces between the number of rows are not encoding in UTF-8
```
<text text-anchor="start" x="275.4835" y="-46.3" font-family="Helvetica,sans-Serif" font-size="11.00" fill="#000000">3 850 330 rows</text>
```
Replacing that mal encoding spaces with a simple space. The graph is shown ok.

No error showed in log even in debug mode.

## Possible Solution

Spaces added to separate thousands of numbers are not in the good encoding. A simple ASCII blank space would be fine for that. Or even the html `&nbsp;` if needed

## Steps to Reproduce (for bugs)

1. Launch jar
2. Wait
3. Graphs generated not OK

## Context

* Database type (e.g. MySQL): Oracle 12 service mode
* Database driver version (is you use a special one): ojdbc7-12.1.0.2.jar
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:  java -jar %SCHEMASPY_LIB%\schemaspy-6.1.0.jar -configFile %SCHEMASPY_CONFIG%\BD.properties -vizjs -debug

## Your Environment

* Version used: 6.1.0
* Environment name and version (e.g. Chrome 39): Any
* Operating System and version (e.g. Windows 10): Windows 10
* Java version: 1.8.0_181

**Comment by npetzall** [comment]
I'm having trouble re-creating the issue, so I need additional information.

Running `java -XshowSettings:properties` in cmd or terminal will print some useful information.
Not all properties may be printed but the parts that will be interesting for me is:
* file.encoding
* sun.jnu.encoding 
* sun.stderr.encoding 
* sun.stdout.encoding 
* user.country
* user.country.format
* user.language
* user.variant

I have found an issue where we write the SVG in the default charset and that might be different from UTF-8 which SVG should be written in. But I would like to be able to re-create the issue so that I can verify that I'm fixing your issue.
