### ISSUE TITLE
Not able to connect SAP HANA DB

### ISSUE THREAD

**Issue by codeking05** [schemaspy/schemaspy#802]
Hi,

Thank you for such a useful tool, I am able to generate ERD for MSSQL, but having the below issue while accessing SAP HANA DB

could you please help me to fix this issue? I placed the required HANA DB properties under _schemaspy-6.1.0\BOOT-INF\classes\org\schemaspy\types_

![image](https://user-images.githubusercontent.com/66556504/142738872-8029b42b-ebc6-4e45-9cbf-2f8ea0e6d016.png)

**Comment by npetzall** [comment]
The last few lines is missing of the stacktrace but since it's a stackoverflow.com i suspect that there is an incorrect extends in your databaseType file or that you've included it in the jar but also have it in the same directory as schemaspy.

There is no reason to have it in the jar, it will be found if it's in the same directory as the schemaspy-jarfile.

**Comment by codeking05** [comment]
Thanks for your response.

The issue is resolved after commenting extends in the hana.properties file
![image](https://user-images.githubusercontent.com/66556504/144290879-d127281b-10ee-4f7a-a060-d00a346ab423.png)
