### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by fkromer** [schemaspy/schemaspy#82]
Is there some "official" or recommended Docker image for SchemaSpy?

**Comment by rafalkasa** [comment]
Hi @fkromer I try to prepare official Docker image to the end of week.

**Comment by fkromer** [comment]
Hi @rafalkasa would be great if that is manageable for you...

**Comment by npetzall** [comment]
@rafalkasa 
I've create a first attempt. However the build more or less requires travis-ci to get a small image. 

I'll change it a bit, so that it will actually download the release from github
I'll start working on a second one that will be built every time master i updated "snapshot".

I just have one question, which I think is a no brainer. Include all drivers that are available on maven?

**Comment by npetzall** [comment]
I've finished with snapshot and release, just gonna add som drivers to the image so that more or less only need to add custom-drivers for oracle or other exotic variant (or older drivers)

**Comment by rafalkasa** [comment]
@npetzall I reviewed your work for me everything looks correct please create PR so we can merge and release official support for the Docker users 😄

**Comment by boaglio** [comment]
this is great news and I am a big fan of SchemaSpy, thank you 😄

**Comment by npetzall** [comment]
@boaglio we have an image on docker hub. Still have docs to write. Dockerfile is in repo the one at hub.docker is incorrect.

**Comment by npetzall** [comment]
@rafalkasa @fkromer Have a look at https://hub.docker.com/r/schemaspy/schemaspy/

**Comment by rafalkasa** [comment]
Thanks to work @npetzall we have Docker image I close the issue.
