### ISSUE TITLE
-template parametter ignored with jar-binary package

### ISSUE THREAD

**Issue by ismailsimsek** [schemaspy/schemaspy#83]
with following line template parameter is ignored  when running program isJarFile.

/schemaspy/src/main/java/org/schemaspy/view/MustacheWriter.java

```
    private String getTemplatePath(String templatePath) {
        String path = "layout/"+templatePath; // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        if (!Config.getInstance().isJarFile()) {
            path = new File(templateDirectory,templatePath).getPath();
        }
        return path;
    }
```

**Comment by rafalkasa** [comment]
@ismailsimsek in my opinion this issue is related to the changes made by @Riggs333 in PR #74.
I need to investigate where is the issue or maybe @Riggs333 you can verify what is going on.

Thanks for rapport the issue.

**Comment by Riggs333** [comment]
Yes, I think this is somehow related because Config#isJarFile always returns true since the PR merge.
I will take a look later this day.

@ismailsimsek Would you please describe the use case in some more detail?
How do you start SchemaSpy and with what parameters?

Thanks!

**Comment by ismailsimsek** [comment]
Hi adding below what i think happening

with following command Config.getInstance().isJarFile()  returns True and the program never goes into if section where templateDirectory (-template) parameter used.

**java -jar schemaspy-6.0.0-rc1-jar-with-dependencies.jar** XXXXXXXX -template "${HOME}/template/MYlayout/"

**Comment by Riggs333** [comment]
Great, thank you! Now I see.
I guess I can provide a fix this evening.

**Comment by Riggs333** [comment]
@rafalkasa @ismailsimsek, please take a look at the pull request.
With this fix I managed to provide a custom layout via the command line parameter `-template`.
When omitting the parameter configuration falls back to the included layout directory.

I would not spend too much effort into fixing the `Config` class by now, because I'm preparing a PR to refactor the whole handling of parameters and configuration stuff.
(see this branch https://github.com/Riggs333/schemaspy/tree/config-refactoring)
