### ISSUE TITLE
Errors when building diagrams

### ISSUE THREAD

**Issue by NilkOne** [schemaspy/schemaspy#833]
Hello,

Any idea why I get errors on diagrams build task ?

```
INFO  - Writing/diagramming details
..................................................................................................................................................
ERROR - dot -Tpng HTTVA.1degree.dot -oHTTVA.1degree.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng HTTVA.1degree.dot -oHTTVA.1degree.png -Tcmapx: in label of node HTTVA
ERROR - dot -Tpng HTTVA.implied1degrees.dot -oHTTVA.implied1degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng HTTVA.implied1degrees.dot -oHTTVA.implied1degrees.png -Tcmapx: in label of node HTTVA
ERROR - dot -Tpng HTTVA.implied2degrees.dot -oHTTVA.implied2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng HTTVA.implied2degrees.dot -oHTTVA.implied2degrees.png -Tcmapx: in label of node HTTVA
....................................................................................................................................................
(102sec)
```

**Comment by npetzall** [comment]
Check the ouput I think it's correct.

The way we call graphviz causes us to only have stdout and errout. So we log anything from errout to error level. But they are only warnings coming from Graphviz.

**Comment by npetzall** [comment]
We should improve handling of warnings from Graphviz.
Not sure how, but I'm guessing that we can assume warnings and decide if there are errors based on exit code maybe.

**Comment by bobhairgrove** [comment]
FWIW, GraphViz with C code can redirect its errors and warnings to a custom user error function (see GraphViz documentation for `agseterrf()`).

I don't know if this can be done with Java or not.

All of the GraphViz errors and warnings begin either with the string **"Error: "** or **"Warning: "**; however, it is difficult to implement a custom error function (in C or C++) because of the way GraphViz handles the memory allocated for the error message. Until version 2.41 (including) there was also a memory leak associated with using the custom error function which was fixed in later versions, I believe.
