### ISSUE TITLE
"Illegal reflective access by org.postgresql.jdbc.TimestampUtils" in current release

### ISSUE THREAD

**Issue by xenomachina** [schemaspy/schemaspy#955]
## Expected Behavior

No warnings.

## Current Behavior

Running the released version of SchemaSpy from (6.1.1, from docker) with a postgres DB results in the following warnings:

>WARNING: An illegal reflective access operation has occurred  
>WARNING: Illegal reflective access by org.postgresql.jdbc.TimestampUtils (file:/drivers_inc/postgresql-42.1.1.jre7.jar) to field java.util.TimeZone.defaultTimeZone  
>WARNING: Please consider reporting this to the maintainers of org.postgresql.jdbc.TimestampUtils  
>WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations  
>WARNING: All illegal access operations will be denied in a future release  

## Possible Solution

1. Make sure the postgres driver being used is new enough to have a fix for [this issue](https://github.com/pgjdbc/pgjdbc/issues/986).
2. [Publish a new release of SchemaSpy](https://github.com/schemaspy/schemaspy/issues/837)

**Comment by npetzall** [comment]
I totally agree with your solutions.

But I don't actually know how you got that warning, there is no release 6.1.1.
There's a 6.1.0 on docker hub, that uses Java 8 which won't cause that warning, the warning was introduced in Java 9.
 
Snapshot has had version 42.2.25 since 7 of Feb, and was bumped to 42.3.5  14 of May.
 
Our docker images are tagged under schemaspy/schemaspy, if you've used a different image, then it's not maintained by us.

**Comment by npetzall** [comment]
Can reproduce with 6.2.1
