### ISSUE TITLE
uppercase in db user name

### ISSUE THREAD

**Issue by szauri** [schemaspy/schemaspy#97]
It looks like schemaspy send db user name in uppercase, even when I set it in lowercase.
my db configfile contains:
schemaspy.u="uzytkownik"

After trying to run there is error: 
org.schemaspy.model.ConnectionFailure: org.netezza.error.NzSQLException: LDAP authentication failed for user 'UZYTKOWNIK'

**Comment by npetzall** [comment]
Version 6.0.0-rc1?

**Comment by szauri** [comment]
with schemaspy-6.0.0-rc1

**Comment by Riggs333** [comment]
@szauri Could you please try to provide the username via command line argument instead of via config file?
Example:
`java -jar schemaspy-6.0.0-rc1.jar -u uzytkownik ...`

If this works we can narrow the bug analysis on the properties file.

Additionally could you provide some information about the operation system you're running SchemaSpy on and which database you're trying to analyze?
The exception message contains `LDAP`, there is also some relevant context information regarding the setup?

Thanks!

**Comment by szauri** [comment]
I'm working on windows 7, and connecting to netezza.
I test it using command line with the same results:
`c:\shemaspy>java -jar schemaspy-6.0.0-rc1.jar -t netezza -dp nzjdbc.jar -db <BAZA> -host <IP> -port <PORT> -u uzytkownik ...`
results:
`cze 02, 2017 11:33:44 AM org.springframework.context.annotation.AnnotationConfig
ApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicat
ionContext@7cd84586: startup date [Fri Jun 02 11:33:44 CEST 2017]; root of conte
xt hierarchy
cze 02, 2017 11:33:44 AM org.schemaspy.Config loadProperties
INFO: Configuration file not found
Using database properties:
  c:\shemaspy\netezza.properties
Failed to connect to database URL [jdbc:netezza://IP:PORT/BAZA]
org.netezza.error.NzSQLException: LDAP authentication failed for user 'UZYTKOWNIK'
....
`

**Comment by rafalkasa** [comment]
I'm afraid that the main issue here is that SchemaSpy doesn't has support for netezza database.

Here you will find list of supported databases https://github.com/schemaspy/schemaspy/tree/master/src/main/resources/org/schemaspy/types

We should build in the documentation section when we can provide list of supported database types.

In my opinion first we need to add configuration file for IBM Netezza database and after you can check it again.

**Comment by szauri** [comment]
I prepared config file for netezza and it works. I tested it on netezza local user.

Problem is with authentication based on LDAP user. LDAP username is case sensitive, and schemaspy upercase my (lowercase) username.

**Comment by npetzall** [comment]
@szauri 
I've debugged version 6.0.0-rc1 and for command-line supplied user it doesn't uppercase the username. 

Since the driver is proprietary I can't actually test if the driver does something funny with the username.

I found this [ldap-troubleshooting](http://dbamanishjaiswal.blogspot.se/2016/04/ldap-troubleshooting-in-ibm-netezza.html)
and this [sysadmin_ldap](https://www.ibm.com/support/knowledgecenter/SSULQD_7.2.0/com.ibm.nz.adm.doc/c_sysadm_ldap_authentication.html)

I know nothing about netezza but found something interesting in [dbuser_set_authentication](https://www.ibm.com/support/knowledgecenter/SSULQD_7.2.0/com.ibm.nz.dbu.doc/r_dbuser_set_authentication.html)

For LDAP you can actually specify if the username is stored in LDAP in upper or lower-case. So it might be netezza that uppercases the username when using LDAP. Also the first link has a command to check which databases/datasources a user has access to, and also most of the links contains path to the netezza log which might contain additional information as to why you get the authentication error.

I hope this helps a bit.

**Comment by npetzall** [comment]
@szauri If you get it working would you mind sharing the database config so that we can add it?

**Comment by rafalkasa** [comment]
@szauri it will be very welcome, if you can prepare the PR with configuration for IBM Netezza it can help others users of SchemaSpy

Usually we are not fixing issues with LDAP and some specific JDBC drivers, so the issue that you have is not directly SchemaSpy related... 

If we can help you somehow please let us know, if not I will close this issue.

**Comment by szauri** [comment]
Schemaspy with netezza works almost "out of the box". My netezza.properties looks like follows (based on postgresql properties).
[netezza.properties.txt](https://github.com/schemaspy/schemaspy/files/1051429/netezza.properties.txt)

**Comment by npetzall** [comment]
@szauri did you figure out the problem with LDAP if so I'm assuming that it had nothing to do with schemaspy and that we can add your properties file to schemaspy.

**Comment by szauri** [comment]
Thanks for help.
