### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by pasvensson** [schemaspy/schemaspy#983]
## Context

* Full command including arguments how you run SchemaSpy:
java -jar./schemaspy-6.1.0.jar -dbhelp

## Your Environment
* Version used: schemaSpy 6.1.0
* Environment name and version (e.g. Chrome 39): openjdk 11.0.17 
* Operating System and version (e.g. Windows 10): Linux (Ubuntu Desktop 22)
* Java version:

**Comment by jesperolsson-se** [comment]
It's possible to create custom `database types` for SchemaSpy. As described [in the documentation](https://schemaspy.readthedocs.io/en/latest/configuration/databaseType.html), you'll need to specify

- a `description`;
- a `connection spec` (a.k.a., a connection string); and
- a `JBDC driver`.

MongoDB does provide a [JBDC driver](https://www.mongodb.com/docs/atlas/data-federation/query/sql/drivers/jdbc/connect/) and a [connection spec](https://www.mongodb.com/docs/manual/reference/connection-string/). So from SchemaSpy's perspective, everything should be fine. However, since MongoDB is a document database, you might need to set some things up from the MongoDB side to ensure there even is a schema.
