### ISSUE TITLE
How to trigger schemaSpy method/interface to generate diagrams without running command.

### ISSUE THREAD

**Issue by itsubaidshahid** [schemaspy/schemaspy#991]
Imported schemaSpy:v5.0.0 maven dependency using this : https://mvnrepository.com/artifact/org.jumpmind.symmetric.schemaspy/schemaspy

Also added the **schemaSpy.properties** file with up to date database properties.
 _But once I run the project Nothing is being generated on the specified path , How to invoke/trigger schemaSpy job using maven dependency._ 
 
 There is no method/interface exposed on how to trigger the schemaSpy job to generate the images in specified directory on some user based input (Could be some database credentials entered by end user in runtime environment to generate relationship diagrams).
 
**Note:**
Its generating diagrams properly while running command in terminal, Wanted to generate the diagrams in runtime environment based on user's input using some exposed methods/interface .

**Comment by npetzall** [comment]
There are a lot of changes done since 5.0.0 and this project started with 6.0.0. So in general we don't support 5.0.

I'm not sure but it sounds like you want to use the exec maven plugin. Since neither 5.0 or 6.0 is a maven plugin.

Just having SchemaSpy as dependency won't trigger anything, that's where the exec plugin comes in.

That is if I understood what you want to accomplish.

If you want to build an application that uses SchemaSpy internally, there isn't a public api for that. But there have been talk about it, but not enough time to realize it.

You can use the concrete classes, but you'll need to dig into the source and I have no idea about the source for the artifact that you've added as a dependency. Moste IDEs has an option to download source if it's attached in maven.

**Comment by itsubaidshahid** [comment]
Can schemaSpy latest version be added as maven dependency ? what I found on the maven repositories is 5.0 version of schemaSpy.

I can sense from above comment that there is no maven dependency for it, we just need to set the path for jar file and execute the command in the code.

**Comment by npetzall** [comment]
It's not published to maven central. But you can have a look at jitpack.io

But if you can specify in more details or in steps what you want maybe I can better assist you.

The thing that I'm having trouble with is the maven part and the user input. Normally you don't want input to a build tool.

But depending on the use case, our docker image might be better suited. Since I can be triggered quite easily by for instance a CI/CD pipeline.

**Comment by itsubaidshahid** [comment]
Resolved this by executing the jar command within Java code, there was no other way as schemaSpy does not provide any public APIs that can be called.
